server {
    listen 80;
    server_name yourlawyeer.ir www.yourlawyeer.ir 37.59.183.158;
    location / {
        proxy_pass http://your-lowyer-frontend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /backend/ {
        proxy_pass http://yourLawyer_fastapi_app:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
